version: '3.9'

services:
  app_manager:
    restart: always
    image: htetlinmaung/app_manager
    build: .
    ports:
      - "7070:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - connection_string=mongodb://mongo:27017/appmanagerdb
      - docker_network=appmanagernet
      - express_handler_mode=native
      - admin_password=User@123
      - jwt_secret=971bdbbf2f9aabaa
      - redis_url=redis://redis:6379
      - docker_username=htetlinmaung
      - docker_password=ZG9ja2VyMjU1MTk5Ngo=
  mongo:
    image: mongo
    restart: always
    # ports:
    #   - "27018:27017"
    volumes:
      - appmgrdb:/data/db
  redis:
    image: redis:alpine
    restart: always

volumes:
  appmgrdb: